# Generated by Django 2.2.5 on 2021-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_champion',
            field=models.CharField(choices=[('GER', 'Deutschland'), ('FRA', 'Frankreich'), ['', '']], default='', max_length=12),
        ),
    ]
