# Generated by Django 2.2 on 2024-04-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Weltmeister',
            new_name='Europameister',
        ),
    ]
