# Generated by Django 2.2.5 on 2022-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Weltmeister',
            field=models.CharField(choices=[('GER', 'Deutschland'), ('FRA', 'Frankreich'), ['---', '---']], default='---', max_length=12),
        ),
    ]
