# Generated by Django 2.2.5 on 2022-09-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220901_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Weltmeister',
            new_name='weltmeister',
        ),
    ]
