# Generated by Django 2.2.5 on 2021-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210527_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='right_tips',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_champion',
            field=models.CharField(choices=[('GER', 'Deutschland'), ('FRA', 'Frankreich'), ('ITA', 'Italien'), ('ESP', 'Spanien'), ['', '']], default='', max_length=12),
        ),
    ]
