# Generated by Django 2.2.5 on 2022-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Champion',
            field=models.CharField(choices=[('GER', 'Deutschland'), ('FRA', 'Frankreich'), ('ITA', 'Italien'), ('ESP', 'Spanien'), ('CRO', 'Kroatien'), ('BEL', 'Belgien'), ('NED', 'Holland'), ['---', '---']], default='---', max_length=12),
        ),
    ]
