# Generated by Django 2.2.5 on 2022-09-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220901_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='weltmeister',
            new_name='Weltmeister',
        ),
    ]
