# Generated by Django 2.2.5 on 2022-07-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220725_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Champion',
            new_name='Weltmeister',
        ),
    ]
