# Generated by Django 2.2.5 on 2022-09-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220725_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Weltmeister',
            new_name='Champion',
        ),
    ]
