# Generated by Django 2.2.5 on 2021-05-25 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('matchday', models.IntegerField(default=0)),
                ('guest_score', models.IntegerField(default=-1)),
                ('home_score', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_ccode', models.CharField(max_length=3)),
                ('win_points', models.IntegerField(default=10)),
                ('eliminated', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tip_home', models.IntegerField(default=-1)),
                ('tip_guest', models.IntegerField(default=-1)),
                ('joker', models.BooleanField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tip_app_main.Match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='guest_team', to='tip_app_main.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='tip_app_main.Team'),
        ),
    ]
