# Generated by Django 2.2.5 on 2021-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip_app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='tip_guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tip_home',
            field=models.IntegerField(default=0),
        ),
    ]
