# Generated by Django 2.2.5 on 2021-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip_app_main', '0002_auto_20210527_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='tip_guest',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tip_home',
            field=models.IntegerField(default=-1),
        ),
    ]
